create_link:
	npm link ${package}
	npm-link-shared ./node_modules/${package}/node_modules . react

link:
	make create_link package="@bolid/mcqueen-icons"
	make create_link package="@bolid/mcqueen-react"
